//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CHITIET_THUEPHONG
    {
        [DisplayName("Số phiếu")]
        public string SO_PHIEU { get; set; }
        [DisplayName("Mã phòng")]
        public string MAPHONG { get; set; }
        [DisplayName("Số người")]
        public byte SONGUOI { get; set; }
        [DisplayName("Giá phòng")]
        public decimal GIAPHONG { get; set; }
    
        public virtual PHONG PHONG { get; set; }
        public virtual PHIEU_THUEPHONG PHIEU_THUEPHONG { get; set; }
    }
}
