//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CHITIET_THUEDICHVU
    {
        [DisplayName("Số phiếu")]
        public string SO_PHIEU { get; set; }
        [DisplayName("Mã dịch vụ")]
        [Required(ErrorMessage = "Chưa nhập mã dịch vụ")]
        public string MA_DICHVU { get; set; }
        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Chưa nhập số lượng")]
        [Range(0, Int16.MaxValue, ErrorMessage = "Số lượng phải lớn hơn 0")]
        public int SOLUONG { get; set; }
        [DisplayName("Giá dịch vụ")]
        public decimal GIA_DICHVU { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual PHIEU_THUEPHONG PHIEU_THUEPHONG { get; set; }
    }
}
