//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_THUE_DICHVU
    {
        public int SO_PHIEU { get; set; }
        public string MA_DICHVU { get; set; }
        public int SOLUONG { get; set; }
        public decimal GIA_DICHVU { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual PHIEU_THUEPHONG PHIEU_THUEPHONG { get; set; }
    }
}
