//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DICHVU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICHVU()
        {
            this.CHITIET_THUEDICHVU = new HashSet<CHITIET_THUEDICHVU>();
        }

        [DisplayName("Mã dịch vụ")]
        [Required(ErrorMessage = "Chưa nhập mã dịch vụ")]
        public string MA_DICHVU { get; set; }
        [DisplayName("Tên dịch vụ")]
        [Required(ErrorMessage = "Chưa nhập tên dịch vụ")]
        public string TEN_DICHVU { get; set; }
        [DisplayName("Giá dịch vụ")]
        [Required(ErrorMessage = "Chưa nhập giá dịch vụ")]
        [Range(0.0, Double.MaxValue, ErrorMessage = "Giá dịch vụ phải lớn hơn 0")]
        public decimal GIA_DICHVU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_THUEDICHVU> CHITIET_THUEDICHVU { get; set; }
    }
}
