//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KHACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACH()
        {
            this.PHIEU_THUEPHONG = new HashSet<PHIEU_THUEPHONG>();
        }

        [DisplayName("Mã khách")]
        [Required(ErrorMessage = "Chưa nhập mã khách")] 
        public string MA_KHACH { get; set; }
        [DisplayName("Họ tên khách")]
        [Required(ErrorMessage = "Chưa nhập họ tên khách")]
        public string HOTEN_KHACH { get; set; }
        [DisplayName("CMND/PASSPORT")]
        [Required(ErrorMessage = "Chưa nhập CMND/PASSPORT")]
        public string CMND { get; set; }
        [DisplayName("Điện thoại")]
        [Required(ErrorMessage = "Chưa nhập điện thoại")]
        public string DIENTHOAI { get; set; }
        [DisplayName("Quốc tịch")]
        [Required(ErrorMessage = "Chưa nhập quốc tịch")]
        public string QUOCTICH { get; set; }
        [DisplayName("Giới tính")]
        public bool GIOITINH { get; set; }
        [DisplayName("Ngày sinh")]
        [Required(ErrorMessage = "Chưa nhập ngày sinh")]
        public System.DateTime NGAYSINH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_THUEPHONG> PHIEU_THUEPHONG { get; set; }
    }
}
