//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_THUEPHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEU_THUEPHONG()
        {
            this.CHITIET_THUEPHONG = new HashSet<CHITIET_THUEPHONG>();
            this.CT_THUE_DICHVU = new HashSet<CT_THUE_DICHVU>();
            this.TONTHATs = new HashSet<TONTHAT>();
        }
    
        public int SO_PHIEU { get; set; }
        public int MAKHACH { get; set; }
        public string MA_NHANVIEN { get; set; }
        public System.DateTime NGAYLAP_PHIEU { get; set; }
        public System.DateTime NGAYDEN { get; set; }
        public System.DateTime NGAYDI { get; set; }
        public Nullable<bool> DATRAPHONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_THUEPHONG> CHITIET_THUEPHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_THUE_DICHVU> CT_THUE_DICHVU { get; set; }
        public virtual KHACH KHACH { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONTHAT> TONTHATs { get; set; }
    }
}
