//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.CHITIET_THUEPHONG = new HashSet<CHITIET_THUEPHONG>();
        }
    
        public string MA_PHONG { get; set; }
        public string MA_LOAIPHONG { get; set; }
        public decimal GIAPHONG { get; set; }
        public string MA_TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_THUEPHONG> CHITIET_THUEPHONG { get; set; }
        public virtual LOAIPHONG LOAIPHONG { get; set; }
        public virtual TRANGTHAI_PHONG TRANGTHAI_PHONG { get; set; }
    }
}
