//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLKS_H2OEntities : DbContext
    {
        public QLKS_H2OEntities()
            : base("name=QLKS_H2OEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIET_THUEDICHVU> CHITIET_THUEDICHVU { get; set; }
        public virtual DbSet<CHITIET_THUEPHONG> CHITIET_THUEPHONG { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<KHACH> KHACHes { get; set; }
        public virtual DbSet<LOAIPHONG> LOAIPHONGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEU_THUEPHONG> PHIEU_THUEPHONG { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<TRANGTHAI_PHONG> TRANGTHAI_PHONG { get; set; }
        public virtual DbSet<VATTU> VATTUs { get; set; }
        public virtual DbSet<VATTU_LOAIPHONG> VATTU_LOAIPHONG { get; set; }
    
        public virtual ObjectResult<THONGKE_DICHVU_Result> THONGKE_DICHVU()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THONGKE_DICHVU_Result>("THONGKE_DICHVU");
        }
    
        public virtual ObjectResult<THONGKE_PHONG_Result> THONGKE_PHONG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THONGKE_PHONG_Result>("THONGKE_PHONG");
        }
    }
}
