//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class VATTU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VATTU()
        {
            this.VATTU_LOAIPHONG = new HashSet<VATTU_LOAIPHONG>();
        }

        [DisplayName("Mã vật tư")]
        [Required(ErrorMessage = "Chưa nhập mã vật tư")]
        public string MA_VATTU { get; set; }
        [DisplayName("Tên vật tư")]
        [Required(ErrorMessage = "Chưa nhập tên vật tư")]
        public string TEN_VATTU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VATTU_LOAIPHONG> VATTU_LOAIPHONG { get; set; }
    }
}
