//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class VATTU_LOAIPHONG
    {
        [DisplayName("Mã vật tư")]
        [Required(ErrorMessage = "Chưa nhập mã vật tư")]
        public string MA_VATTU { get; set; }
        [DisplayName("Loại phòng")]
        public string MA_LOAIPHONG { get; set; }
        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Chưa nhập số lượng")]
        [Range(0, Byte.MaxValue, ErrorMessage = "Số lượng phải lớn hơn 0")]
        public byte SOLUONG { get; set; }
    
        public virtual LOAIPHONG LOAIPHONG { get; set; }
        public virtual VATTU VATTU { get; set; }
    }
}
