//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS_H2O.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATTU_LOAIPHONG
    {
        public string MA_VATTU { get; set; }
        public string MA_LOAIPHONG { get; set; }
        public byte SOLUONG { get; set; }
    
        public virtual LOAIPHONG LOAIPHONG { get; set; }
        public virtual VATTU VATTU { get; set; }
    }
}
